[package]
name = "soft-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"
im-rc = "15.1.0"
itertools = "0.10.5"
thiserror = "1.0.40"
